import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillWechat,
  AiFillInstagram,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public//dev-ed-wave.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xinyun Zhang Protofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-gradient-to-b from-white xto-teal-50 px-10">
        <section className=" xbg-blue-700 min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">DevelopedbyXinyunZhang</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className=" font-burtons bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
              <li>
                <a
                  className="font-burtons bg-gradient-to-r  from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  LindedIn
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10 ">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium ">
              Xinyun Zhang
            </h2>
            <h3 className=" text-2xl py-2">Developer and Designer.</h3>
            <p className=" text-md py-5 leading-8 text-gray-800">
              about me...{" "}
            </p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            {/* <AiFillTwitterCircle /> */}
            <AiFillInstagram />
            <AiFillLinkedin />
            {/* <AiFillYoutube /> */}
            <AiFillGithub href="https://github.com/XinYun2020" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
          <section>
            <div>
              <h3 className=" text-3xl py-1 ">Tech Skill Sets</h3>
              <p className="text-md py-2 leading-8 text-gray-800 xdark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
            </div>
          </section>
        </section>
      </main>
    </div>
  );
}
