import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiFillWechat } from "react-icons/ai";
import Image from "next/image";
import { useState } from "react";
import { BsPersonFill } from "react-icons/bs";
import { MenuButton } from "../components/MenuButton";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false); // TODO: Context for darkMode

  const ViewContainer = (props) => {
    return (
      <>
        <section className=" min-h-screen">
          <div className=" px-20 md:px-36 lg:px-56 pb-24">
            <div>{props.children}</div>
          </div>
        </section>
      </>
    );
  };

  const ButtonGrid = (props) => {
    return (
      <>
        <div
          className=" grid 
          lg:grid-cols-3 
          gap-4 "
        >
          {props.children}
        </div>
      </>
    );
  };

  const CardContainer = (props) => {
    return (
      <>
        <div className=" overflow-hidden rounded-sm bg-white border border-gray-border text-center mb-5  ">
          {props.children}
        </div>
      </>
    );
  };

  const CardHeader = (props) => {
    return (
      <>
        <div
          className=" py-2 px-3
        bg-gray-card border-b
         border-gray-border"
        >
          <h2 className=" text-left font-medium text-gray-font">
            header{props.children}
          </h2>
        </div>
      </>
    );
  };

  const CardBody = (props) => {
    return (
      <>
        <div className="pt-4 pb-5 px-4 rounded-sm">{props.children}</div>
      </>
    );
  };

  const UserContainer = (props) => {
    return (
      <>
        <div className=" flex flex-row justify-between pt-24 pb-16">
          {props.children}
        </div>
      </>
    );
  };

  const UserName = (props) => {
    return (
      <>
        <h2 className=" text-gray-font text-5xl font-semibold">
          Alice Zhang{props.children}
        </h2>
      </>
    );
  };

  const UserRole = (props) => {
    return (
      <>
        <div className="flex flex-row gap-6 align-middle text-lg pt-3 text-gray-font">
          <span className="flex flex-row gap-1 ">
            <BsPersonFill className=" text-4xl" />
            <h3 className="my-auto relative text-3xl">Admin{props.children}</h3>
          </span>
        </div>
      </>
    );
  };

  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Tailwind</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <ViewContainer>
            <UserContainer>
              <UserName></UserName>
              <UserRole></UserRole>
            </UserContainer>

            <CardContainer>
              <CardHeader />
              <CardBody>
                <ButtonGrid>
                  <MenuButton></MenuButton>
                  <MenuButton newFeature={true} />
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                </ButtonGrid>
              </CardBody>
            </CardContainer>

            <CardContainer>
              <CardHeader />
              <CardBody>
                <ButtonGrid>
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                  <MenuButton />
                </ButtonGrid>
              </CardBody>
            </CardContainer>
          </ViewContainer>
        </main>
      </div>
    </>
  );
}
